events {}

http {
    server {
        listen 80;
        server_name 107.21.67.134;

        # OTOMATIS TAMBAH SLASH (Mencegah Kepental ke WP)
        location = /pma {
            return 301 $scheme://$http_host/pma/;
        }

        # KONFIGURASI PMA
        location /pma/ {
            proxy_pass http://pma/; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # Memaksa redirect internal PMA tetap di folder /pma/
            proxy_redirect / /pma/;
        }

        # KONFIGURASI WORDPRESS
        location / {
            proxy_pass http://wp:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
