events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # 1. Jalur untuk phpMyAdmin
        location /pma/ {
            proxy_pass http://pma/; # PENTING: Ada '/' di akhir pma/
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # 2. Jalur untuk WordPress (Default)
        location / {
            proxy_pass http://wp:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
