server {
    listen 80;

    # HANDLE /pma (dengan atau tanpa slash)
location /pma/ {
            proxy_pass http://pma/; # Pastikan ada slash di akhir
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # --- INI KUNCINYA ---
            # Jika PMA minta redirect ke '/', Nginx ubah jadi '/pma/'
            proxy_redirect / /pma/;
            # Pastikan cookie session tetap valid di path /pma/
            proxy_cookie_path / /pma/;
        }
    }


    # WORDPRESS DEFAULT
    location / {
        proxy_pass http://wp;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
